### ISSUE TITLE
WAN Training: CUDA OOM error using block swapping

### ISSUE THREAD

**Issue by djasil** [kohya-ss/musubi-tuner#202]
I'm using WSL with a 4080 GPU and 32GB of available RAM, but I'm getting CUDA OOM error when using blocks_to_swap.

**free -h --giga**
```
total        used        free      shared  buff/cache   available
Mem:             32G        615M         31G        2.0M        123M         31G
Swap:           8.2G         49M        8.1G
```
**nvidia-smi**
```
Sun Mar 30 15:30:41 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.86.16              Driver Version: 572.16         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080        On  |   00000000:08:00.0  On |                  N/A |
|  0%   42C    P8             14W /  320W |     595MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A              30      G   /Xwayland                             N/A      |
+-----------------------------------------------------------------------------------------+
```

```
python wan_cache_latents.py --dataset_config /home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/s1llywlk.toml --vae /home/wsl_aitools/musubi-tuner/training_files/weights/vae/wan_2.1_vae.safetensors
```

```
python wan_cache_text_encoder_outputs.py --dataset_config /home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/s1llywlk.toml --t5 /home/wsl_aitools/musubi-tuner/training_files/weights/t5/models_t5_umt5-xxl-enc-bf16.pth --batch_size 8
```

```
accelerate launch --num_cpu_threads_per_process 1 --mixed_precision bf16 wan_train_network.py --task t2v-14B \
	--dit /home/wsl_aitools/musubi-tuner/training_files/weights/dit/wan2.1_t2v_14B_fp8_e4m3fn.safetensors \
	--dataset_config /home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/s1llywlk.toml \
	--sdpa --mixed_precision bf16 --blocks_to_swap 16 --optimizer_type adamw8bit \
	--learning_rate 1e-4 --fp8_t5 --fp8_base --gradient_checkpointing \
	--max_data_loader_n_workers 2 --persistent_data_loader_worker --network_module networks.lora_wan \
	--network_dim 32 --network_alpha 32 --timestep_sampling shift --discrete_flow_shift 3.0 \
	--max_train_steps 2000 --save_every_n_steps 100 --seed 42 --network_args loraplus_lr_ratio=4 \
	--logging_dir /home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/logging \
	--output_dir /home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/output --output_name s1llywlk
```
OUTPUT:
```
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Trying to import sageattention
Successfully imported sageattention
INFO:wan.modules.model:Detected DiT dtype: torch.float8_e4m3fn
INFO:hv_train_network:Load dataset config from /home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/s1llywlk.toml
INFO:dataset.image_video_dataset:glob videos in /home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/datasets/vid/01
INFO:dataset.image_video_dataset:found 1 videos
INFO:dataset.image_video_dataset:glob videos in /home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/datasets/vid/02
INFO:dataset.image_video_dataset:found 1 videos
INFO:dataset.image_video_dataset:glob videos in /home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/datasets/vid/03
INFO:dataset.image_video_dataset:found 1 videos
INFO:dataset.config_utils:[Dataset 0]
  is_image_dataset: False
  resolution: (320, 240)
  batch_size: 1
  num_repeats: 1
  caption_extension: ".txt"
  enable_bucket: True
  bucket_no_upscale: False
  cache_directory: "/home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/cache/vid/01"
  debug_dataset: False
    video_directory: "/home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/datasets/vid/01"
    video_jsonl_file: "None"
    control_directory: "None"
    target_frames: (49,)
    frame_extraction: full
    frame_stride: 1
    frame_sample: 1
    max_frames: 129

[Dataset 1]
  is_image_dataset: False
  resolution: (320, 240)
  batch_size: 1
  num_repeats: 1
  caption_extension: ".txt"
  enable_bucket: True
  bucket_no_upscale: False
  cache_directory: "/home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/cache/vid/02"
  debug_dataset: False
    video_directory: "/home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/datasets/vid/02"
    video_jsonl_file: "None"
    control_directory: "None"
    target_frames: (25,)
    frame_extraction: full
    frame_stride: 1
    frame_sample: 1
    max_frames: 129

[Dataset 2]
  is_image_dataset: False
  resolution: (320, 240)
  batch_size: 1
  num_repeats: 1
  caption_extension: ".txt"
  enable_bucket: True
  bucket_no_upscale: False
  cache_directory: "/home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/cache/vid/03"
  debug_dataset: False
    video_directory: "/home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/datasets/vid/03"
    video_jsonl_file: "None"
    control_directory: "None"
    target_frames: (37,)
    frame_extraction: full
    frame_stride: 1
    frame_sample: 1
    max_frames: 129


INFO:dataset.image_video_dataset:bucket: (320, 240, 33), count: 1
INFO:dataset.image_video_dataset:total batches: 1
INFO:dataset.image_video_dataset:bucket: (320, 240, 17), count: 1
INFO:dataset.image_video_dataset:total batches: 1
INFO:dataset.image_video_dataset:bucket: (320, 240, 25), count: 1
INFO:dataset.image_video_dataset:total batches: 1
INFO:hv_train_network:preparing accelerator
accelerator device: cuda
INFO:hv_train_network:DiT precision: torch.bfloat16, weight precision: torch.float8_e4m3fn
INFO:hv_train_network:Loading DiT model from /home/wsl_aitools/musubi-tuner/training_files/weights/dit/wan2.1_t2v_14B_fp8_e4m3fn.safetensors
INFO:wan.modules.model:Creating WanModel
INFO:wan.modules.model:Loading DiT model from /home/wsl_aitools/musubi-tuner/training_files/weights/dit/wan2.1_t2v_14B_fp8_e4m3fn.safetensors, device=cpu, dtype=torch.float8_e4m3fn
INFO:wan.modules.model:Loaded DiT model from /home/wsl_aitools/musubi-tuner/training_files/weights/dit/wan2.1_t2v_14B_fp8_e4m3fn.safetensors, info=<All keys matched successfully>
INFO:hv_train_network:enable swap 16 blocks to CPU from device: cuda
WanModel: Block swap enabled. Swapping 16 blocks out of 40 blocks. Supports backward: True
import network module: networks.lora_wan
INFO:networks.lora:create LoRA network. base dim (rank): 32, alpha: 32.0
INFO:networks.lora:neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
INFO:networks.lora:create LoRA for U-Net/DiT: 400 modules.
INFO:networks.lora:LoRA+ UNet LR Ratio: 4.0
INFO:networks.lora:enable LoRA for U-Net: 400 modules
WanModel: Gradient checkpointing enabled.
prepare optimizer, data loader etc.
INFO:hv_train_network:use 8-bit AdamW optimizer | {}
INFO:hv_train_network:casting model to torch.float8_e4m3fn
Traceback (most recent call last):
  File "/home/wsl_aitools/musubi-tuner/wan_train_network.py", line 442, in <module>
    trainer.train(args)
  File "/home/wsl_aitools/musubi-tuner/hv_train_network.py", line 1608, in train
    accelerator.unwrap_model(transformer).prepare_block_swap_before_forward()
  File "/home/wsl_aitools/musubi-tuner/wan/modules/model.py", line 708, in prepare_block_swap_before_forward
    self.offloader.prepare_block_devices_before_forward(self.blocks)
  File "/home/wsl_aitools/musubi-tuner/modules/custom_offloading_utils.py", line 244, in prepare_block_devices_before_forward
    weighs_to_device(b, "cpu")  # make sure weights are on cpu
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wsl_aitools/musubi-tuner/modules/custom_offloading_utils.py", line 105, in weighs_to_device
    module.weight.data = module.weight.data.to(device, non_blocking=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/wsl_aitools/miniconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/wsl_aitools/miniconda3/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/wsl_aitools/miniconda3/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/home/wsl_aitools/miniconda3/lib/python3.12/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/wsl_aitools/miniconda3/bin/python', 'wan_train_network.py', '--task', 't2v-14B', '--dit', '/home/wsl_aitools/musubi-tuner/training_files/weights/dit/wan2.1_t2v_14B_fp8_e4m3fn.safetensors', '--dataset_config', '/home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/s1llywlk.toml', '--sdpa', '--mixed_precision', 'bf16', '--blocks_to_swap', '16', '--optimizer_type', 'adamw8bit', '--learning_rate', '1e-4', '--fp8_t5', '--fp8_base', '--gradient_checkpointing', '--max_data_loader_n_workers', '2', '--persistent_data_loader_worker', '--network_module', 'networks.lora_wan', '--network_dim', '32', '--network_alpha', '32', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.0', '--max_train_steps', '2000', '--save_every_n_steps', '100', '--seed', '42', '--network_args', 'loraplus_lr_ratio=4', '--logging_dir', '/home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/logging', '--output_dir', '/home/wsl_aitools/musubi-tuner/training_files/training_s1llywlk/output', '--output_name', 's1llywlk']' returned non-zero exit status 1.
```
I tried accelerate with different parameters (xformers, flash_att, change the # of blocks...).

It works if I don't use blocks_to_swap, but the training takes forever.

**Comment by djasil** [comment]
Indeed, reducing the dataset did the trick (same duration with half the resolution), though it's still slow on WSL for some reason, even after increasing the RAM to 48GB.

I decided to try it on Windows, and it was much faster. The test with OOM from before, with the same dataset and parameters, also worked with a lot of free RAM left.

I'll run a few more tests on WSL later. At least the Windows environment is now a good alternative.
