### ISSUE TITLE
ValueError: When using DeepSpeed, `accelerate.prepare()` requires you to pass at least one of training or evaluation dataloaders with `batch_size` attribute returning an integer value

### ISSUE THREAD

**Issue by paul-lupu** [kohya-ss/musubi-tuner#44]
Hello, please see bellow: 

Also, side question, for videos, when specifying: `target_frames    = [1,25,45]`, does that mean it will only take 3 frames from each video? 

Command and stack trace:

 ```
accelerate launch --num_cpu_threads_per_process 1 --mixed_precision bf16 \
hv_train_network.py --dit ckpts/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt \
    --dataset_config ./dataset.toml --sdpa --mixed_precision bf16 --fp8_base \
    --optimizer_type adamw8bit --learning_rate 2e-4 --gradient_checkpointing \
    --max_data_loader_n_workers 2 --persistent_data_loader_workers \
    --network_module networks.lora --network_dim 32 \
    --timestep_sampling shift --discrete_flow_shift 7.0  \
    --max_train_epochs 16 --save_every_n_epochs 1 --seed 42 \
    --output_dir output --output_name dance


[2025-01-17 17:42:20,921] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Trying to import sageattention
Successfully imported sageattention
INFO:__main__:Load dataset config from dataset.toml
INFO:dataset.image_video_dataset:glob images in /home/ubuntu/hunyuan-lora-training/musubi-tuner/data/input
INFO:dataset.image_video_dataset:found 4 videos
INFO:dataset.config_utils:[Dataset 0]
  is_image_dataset: False
  resolution: (1024, 576)
  batch_size: 1
  num_repeats: 1
  caption_extension: ".txt"
  enable_bucket: True
  bucket_no_upscale: False
  cache_directory: "/home/ubuntu/hunyuan-lora-training/musubi-tuner/cache"
  debug_dataset: False
    video_directory: "/home/ubuntu/hunyuan-lora-training/musubi-tuner/data/input"
    video_jsonl_file: "None"
    target_frames: [1, 25, 45]
    frame_extraction: head
    frame_stride: 1
    frame_sample: 1


INFO:dataset.image_video_dataset:bucket: (576, 1024, 1), count: 4
INFO:dataset.image_video_dataset:bucket: (576, 1024, 25), count: 4
INFO:dataset.image_video_dataset:bucket: (576, 1024, 45), count: 4
INFO:dataset.image_video_dataset:total batches: 12
INFO:__main__:preparing accelerator
[2025-01-17 17:42:24,654] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-01-17 17:42:25,357] [INFO] [comm.py:652:init_distributed] cdb=None
[2025-01-17 17:42:25,357] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
accelerator device: cuda:0
INFO:__main__:DiT precision: torch.bfloat16, weight precision: torch.float8_e4m3fn
INFO:__main__:Loading DiT model from ckpts/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt
Using torch attention mode, split_attn: False
import network module: networks.lora
INFO:networks.lora:create LoRA network. base dim (rank): 32, alpha: 1
INFO:networks.lora:neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
INFO:networks.lora:create LoRA for U-Net/DiT: 240 modules.
INFO:networks.lora:enable LoRA for U-Net: 240 modules
HYVideoDiffusionTransformer: Gradient checkpointing enabled.
prepare optimizer, data loader etc.
INFO:__main__:use 8-bit AdamW optimizer | {}
override steps. steps for 16 epochs is / 指定エポックまでのステップ数: 192
INFO:__main__:casting model to torch.float8_e4m3fn
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/hunyuan-lora-training/musubi-tuner/hv_train_network.py", line 2362, in <module>
[rank0]:     trainer.train(args)
[rank0]:   File "/home/ubuntu/hunyuan-lora-training/musubi-tuner/hv_train_network.py", line 1324, in train
[rank0]:     transformer = accelerator.prepare(transformer)
[rank0]:   File "/home/ubuntu/hunyuan-lora-training/musubi-tuner/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1333, in prepare
[rank0]:     result = self._prepare_deepspeed(*args)
[rank0]:   File "/home/ubuntu/hunyuan-lora-training/musubi-tuner/venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1689, in _prepare_deepspeed
[rank0]:     raise ValueError(
[rank0]: ValueError: When using DeepSpeed, `accelerate.prepare()` requires you to pass at least one of training or evaluation dataloaders with `batch_size` attribute returning an integer value or alternatively set an integer value in `train_micro_batch_size_per_gpu` in the deepspeed config file or assign integer value to `AcceleratorState().deepspeed_plugin.deepspeed_config['train_micro_batch_size_per_gpu']`.
[rank0]:[W117 17:42:58.347485380 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E0117 17:42:59.144000 56972 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 57010) of binary: /home/ubuntu/hunyuan-lora-training/musubi-tuner/venv/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/hunyuan-lora-training/musubi-tuner/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/hunyuan-lora-training/musubi-tuner/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/ubuntu/hunyuan-lora-training/musubi-tuner/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1153, in launch_command
    deepspeed_launcher(args)
  File "/home/ubuntu/hunyuan-lora-training/musubi-tuner/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 846, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/ubuntu/hunyuan-lora-training/musubi-tuner/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/ubuntu/hunyuan-lora-training/musubi-tuner/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/hunyuan-lora-training/musubi-tuner/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
hv_train_network.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-01-17_17:42:59
  host      : ubuntu-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 57010)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by Sarania** [comment]
I'm not sure if deepspeed works well with Musubi, I'll leave that to kohya to answer, but regarding your other question, what
target_frames  = [1,25,45] will do depends on what frame_extraction you are using. If it's "head" for instance, it will take three samples from each video, all beginning at the start(the "head"), one with a single frame length, one 25 frames long, and one 45 frames long. If you do target_frames = [25,45] and set it to "chunk" it will extract as many 25 frame chunks as possible from each video without overlap, then as many 45 frame chunks as possible from each video. The others are a bit more complex, you can read about all of them here: https://github.com/kohya-ss/musubi-tuner/blob/main/dataset/dataset_config.md#frame_extraction-options

**Comment by paul-lupu** [comment]
@Sarania wait wait, I'm confused: https://github.com/kohya-ss/musubi-tuner; on the Readme it says to run with accelerate launch, which is deepspeed... as far as i understand? I didnt try to add it, just edited the provided example: 
```Start training using the following command (input as a single line):

accelerate launch --num_cpu_threads_per_process 1 --mixed_precision bf16 hv_train_network.py 
    --dit path/to/ckpts/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt 
    --dataset_config path/to/toml --sdpa --mixed_precision bf16 --fp8_base 
    --optimizer_type adamw8bit --learning_rate 2e-4 --gradient_checkpointing 
    --max_data_loader_n_workers 2 --persistent_data_loader_workers 
    --network_module networks.lora --network_dim 32 
    --timestep_sampling shift --discrete_flow_shift 7.0 
    --max_train_epochs 16 --save_every_n_epochs 1 --seed 42
    --output_dir path/to/output_dir --output_name name-of-lora```

Thanks for explaining the frame stuff, makes sense now.

**Comment by Sarania** [comment]
> [@Sarania](https://github.com/Sarania) wait wait, I'm confused: https://github.com/kohya-ss/musubi-tuner; on the Readme it says to run with accelerate launch, which is deepspeed... as far as i understand? I didnt try to add it, just edited the provided example:
> 
> ```
> 
> accelerate launch --num_cpu_threads_per_process 1 --mixed_precision bf16 hv_train_network.py 
>     --dit path/to/ckpts/hunyuan-video-t2v-720p/transformers/mp_rank_00_model_states.pt 
>     --dataset_config path/to/toml --sdpa --mixed_precision bf16 --fp8_base 
>     --optimizer_type adamw8bit --learning_rate 2e-4 --gradient_checkpointing 
>     --max_data_loader_n_workers 2 --persistent_data_loader_workers 
>     --network_module networks.lora --network_dim 32 
>     --timestep_sampling shift --discrete_flow_shift 7.0 
>     --max_train_epochs 16 --save_every_n_epochs 1 --seed 42
>     --output_dir path/to/output_dir --output_name name-of-lora```
> ```
> 
> Thanks for explaining the frame stuff, makes sense now.
> 
> Edit: tried running the train command without accelerate launch and even removed deepspeed with pip but now it's complaining it's not there, so it seems like `hv_train_network.py ` is using it.

Sorry it can be a bit complex so let me explain better, my bad.

Accelerate is not deepspeed, but accelerate can invoke deepspeed if it's config tells it to do so. Accelerate is a platform for managing assigning models to device and various optimizations. Which ones it invokes depend on what it's config tells it to do. Since you don't know what's going on, you likely have a default config that's invoking deepspeed. Try this. Take the following:

```
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: 'NO'
downcast_bf16: 'no'
enable_cpu_affinity: true
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

Put it in a file and save it as 'default.yaml' in the musubi tuner folder. Then change your accelerate launch so it's like this

```
accelerate launch --config_file ./default.yaml hv_train_network.py 
```

with the rest after that point being the same. See if that helps, that should avoid invoking deepspeed.

**Comment by paul-lupu** [comment]
@Sarania  Oh i see; found where the issue was coming from too. Turns out I had trained hotshot's animatediff model previously and had a lingering config file for accelerate under /home/ubuntu/.cache; once I deleted that it all cleared. 

I'll close this one and open a new one for OOM XD

Thanks for clarifying!
